subtitle: 'aeDNA pipeline'
intro_text: 'QC report'
no_version_check: true
plots_force_interactive: True
max_table_rows: 10000
log_filesize_limit: 50000000
ignore_images: False



report_header_info:
  - Contact E-mail: "cggbinf@list.ku.dk"
#  - Application Type: "RNA-seq"
  - Project Type: "aeDNA"
  - Sequencing Platform: "NovaSeq 6000"
#  - Sequencing Setup: "2x100"



sp:
  fastp:
    fn_re: ".+_[sp]e.json$"



extra_fn_clean_exts:
  - '_se.settings'  ## AdapterRemoval
  - '_pe.settings'  ## AdapterRemoval
  - '_pe'           ## FastP
  - '.add_rg'       ## AddReplaceReadGroups
  - '.metrics.txt'  ## BamSorMaDup / Picard MarkDuplicates
  - '.grp'          ## GATK BQSR
  - '.cram'



table_cond_formatting_rules:
  mqc-generalstats-picard-PCT_PF_READS_ALIGNED:
    warn:
      - lt: 0.9
    fail:
      - lt: 0.5
  mqc-generalstats-bamsormadup-PERCENT_DUPLICATION:
    warn:
      - gt: 25
    fail:
      - gt: 50
  mqc-generalstats-fastqc_trimmed-percent_duplicates:
    warn:
      - gt: 25
    fail:
      - gt: 50



table_cond_formatting_colours:
  - blue: '#337ab7'
  - lbue: '#5bc0de'
  - pass: '#5cb85c'
  - warn: '#f0ad4e'
  - fail: '#d9534f'



## To remove a section of a module
# https://multiqc.info/docs/#removing-modules-or-sections
module_order:
  - samtools

  - picard

  - biobambam2:
      name: 'BamSorMaDup'
      path_filters:
        - '*.metrics.txt'

  - bowtie2

  - nonpareil:
      name: 'nonpareil (low complexity)'
      anchor: 'low_complexity'
      info: 'nonpareil results after removing low complexity reads.'
      path_filters:
        - '*/low_complexity/*'

  - bbmap:
      name: 'BBDuk'
      anchor: 'low_complexity'
      info: 'Remove low complexity reads.'
      path_filters:
        - '*/low_complexity/*'

  - nonpareil:
      name: 'nonpareil (represent. read)'
      anchor: 'repres'
      info: 'nonpareil results for representative reads.'
      path_filters:
        - '*/represent/grep/*'

  - nonpareil:
      name: 'nonpareil (dereplicated)'
      anchor: 'derep'
      info: 'nonpareil results for dereplicated reads.'
      path_filters:
        - '*/derep/seqkit/*'
        - '*/derep/vsearch/*'

  - nonpareil:
      name: 'nonpareil (extension)'
      anchor: 'extension'
      info: 'nonpareil results for extended reads.'
      path_filters:
        - '*/extend/tadpole/*'

  - nonpareil:
      name: 'nonpareil'
      anchor: 'initial'
      info: 'nonpareil results for starting reads.'
      path_filters:
        - '*/merge_lanes/*'

  - fastqc:
      name: 'FastQC (trimmed)'
      anchor: 'trimmed'
      info: 'FastQC results AFTER adapter trimming and QC.'
      path_filters:
        - '*/fastqc_trim/*'

  - adapterRemoval

  - bbmap:
      name: 'BBDuk'
      path_filters:
        - '*/trim/*'

  - cutadapt

  - fastp

  - trimmomatic

  - fastqc:
      name: 'FastQC (raw)'
      anchor: 'raw'
      info: 'FastQC results BEFORE adapter trimming and QC.'
      path_filters:
        - '*/fastqc_raw/*'



table_columns_visible:
  picard:
    PCT_PF_READS_ALIGNED:    True
    file_validation_status:  False
  Samtools Flagstat:
    mapped_passed:           True
  FastQC (trimmed):
    percent_duplicates:      False
    avg_sequence_length:     True
    median_sequence_length:  False
  FastQC (raw):
    percent_duplicates:      False
    avg_sequence_length:     False
    median_sequence_length:  False
    percent_gc:              False
    total_sequences:         False



table_columns_placement:
  Picard:
    file_validation_status:  2130
    summed_median:           2140
    summed_mean:             2150
    file_validation_status:  2160
    WARNING_count:           2190
    ERROR_count:             2190
  BamSorMaDup:
    PERCENT_DUPLICATION:     2300
  Samtools Flagstat:
    mapped_passed:           2400
  FastQC (trimmed):
    percent_duplicates:      2600
    percent_gc:              2610
    avg_sequence_length:     2620
    median_sequence_length:  2630
    percent_fails:           2640
    total_sequences:         2650
  FastQC (raw):
    percent_duplicates:      2700
    percent_gc:              2710
    avg_sequence_length:     2720
    median_sequence_length:  2730
    percent_fails:           2740
    total_sequences:         2750



## Module specific configs
nonpareil:
  plot_observed: True
  plot_model: True
  plot_dispersion: 'ci95'
