subtitle: 'aeDNA pipeline'
intro_text: 'QC report'
no_version_check: true
plots_force_interactive: True
max_table_rows: 10000
log_filesize_limit: 50000000
ignore_images: False



report_header_info:
  - Contact E-mail: "cggbinf@list.ku.dk"
#  - Application Type: "RNA-seq"
  - Project Type: "aeDNA"
  - Sequencing Platform: "NovaSeq 6000"
#  - Sequencing Setup: "2x100"



sp:
  fastp:
    fn_re: ".+_[sp]e.json$"



extra_fn_clean_exts:
  - '_se.settings'  ## AdapterRemoval
  - '_pe.settings'  ## AdapterRemoval
  - '_pe'           ## FastP
  - '.add_rg'       ## AddReplaceReadGroups
  - '.metrics.txt'  ## BamSorMaDup / Picard MarkDuplicates
  - '.grp'          ## GATK BQSR
  - '.cram'



table_cond_formatting_rules:
  mqc-generalstats-picard-PCT_PF_READS_ALIGNED:
    warn:
      - lt: 0.9
    fail:
      - lt: 0.5
  mqc-generalstats-bamsormadup-PERCENT_DUPLICATION:
    warn:
      - gt: 25
    fail:
      - gt: 50
  mqc-generalstats-fastqc_trimmed-percent_duplicates:
    warn:
      - gt: 25
    fail:
      - gt: 50



table_cond_formatting_colours:
  - blue: '#337ab7'
  - lbue: '#5bc0de'
  - pass: '#5cb85c'
  - warn: '#f0ad4e'
  - fail: '#d9534f'



## To remove a section of a module
# https://multiqc.info/docs/#removing-modules-or-sections
module_order:
  - samtools:
      name: 'Samtools'
      anchor: 'euk-samtools'
      info: 'Samtools stats.'
      path_filters:
        - '*/aligns/*'

  - bowtie2:
      name: 'Bowtie2'
      anchor: 'euk-bowtie2'
      path_filters:
        - '*/shards/*'

  - fastqc:
      name: 'FastQC (prefilter)'
      anchor: 'prefilter-fastqc'
      info: 'FastQC results after prefiltering.'
      path_filters:
        - '*/prefilter/*'

  - samtools:
      name: 'Samtools (prefilter)'
      anchor: 'prefilter-samtools'
      info: 'Samtools stats after prefiltering.'
      path_filters:
        - '*/prefilter_aligns/*'

  - bowtie2:
      name: 'Bowtie2 (prefilter)'
      anchor: 'prefilter-bowtie2'
      info: 'Bowtie2 results after prefiltering.'
      path_filters:
        - '*/prefilter_shards/*'

  - nonpareil:
      name: 'nonpareil (low complexity)'
      anchor: 'low_complexity-nonpareil'
      info: 'nonpareil results after removing low complexity reads.'
      path_filters:
        - '*/low_complexity/*'

  - fastqc:
      name: 'FastQC (low complexity)'
      anchor: 'low_complexity-fastqc'
      info: 'FastQC results after removing low complexity reads.'
      path_filters:
        - '*/low_complexity/*'

  - bbtools:
      name: 'BBTools (low complexity)'
      anchor: 'low_complexity'
      info: 'Remove low complexity reads.'
      path_filters:
        - '*/low_complexity/*'

  - bbmap:
      name: 'BBTools (low complexity)'
      anchor: 'low_complexity'
      info: 'Remove low complexity reads.'
      path_filters:
        - '*/low_complexity/*'

  - nonpareil:
      name: 'nonpareil (represent. read)'
      anchor: 'represent_read-nonpareil'
      info: 'nonpareil results for representative reads.'
      path_filters:
        - '*/represent/grep/*'

  - fastqc:
      name: 'FastQC (represent. read)'
      anchor: 'represent_read-fastqc'
      info: 'FastQC results for representative reads.'
      path_filters:
        - '*/represent/grep/*'

  - nonpareil:
      name: 'nonpareil (dereplicated)'
      anchor: 'derep-nonpareil'
      info: 'nonpareil results for dereplicated reads.'
      path_filters:
        - '*/derep/*'

  - fastqc:
      name: 'FastQC (dereplicated)'
      anchor: 'derep-fastqc'
      info: 'FastQC results for dereplicated reads.'
      path_filters:
        - '*/derep/*'

  - nonpareil:
      name: 'nonpareil (read extension)'
      anchor: 'read_extension-nonpareil'
      info: 'nonpareil results for extended reads.'
      path_filters:
        - '*/extend/tadpole/*'

  - fastqc:
      name: 'FastQC (read extension)'
      anchor: 'read_extension-fastqc'
      info: 'FastQC results AFTER read extension.'
      path_filters:
        - '*/extend/tadpole/*'

  - nonpareil:
      name: 'nonpareil (merged lanes)'
      anchor: 'merge_lanes-nonpareil'
      info: 'nonpareil results for all reads after trimming and QC.'
      path_filters:
        - '*/merge_lanes/*'

  - fastqc:
      name: 'FastQC (merged lanes)'
      anchor: 'merge_lanes-fastqc'
      info: 'FastQC results for all reads after trimming and QC.'
      path_filters:
        - '*/merge_lanes/*'

  - fastqc:
      name: 'FastQC (trim)'
      anchor: 'trim-fastqc'
      info: 'FastQC results AFTER adapter trimming and QC.'
      path_filters:
        - '*/trim/*'

  - adapterremoval

  - bbmap:
      name: 'BBDuk'
      path_filters:
        - '*/trim/*'

  - cutadapt

  - fastp

  - trimmomatic

  - fastqc:
      name: 'FastQC (raw)'
      anchor: 'raw-fastqc'
      info: 'FastQC results BEFORE adapter trimming and QC.'
      path_filters:
        - '*/raw/*'


## Module specific configs
nonpareil:
  plot_observed: True
  plot_model: True
  plot_dispersion: 'ci95'
