import pandas as pd
from urllib.parse import urlparse, urlunparse

snakemake.utils.min_version("9.22.0")


# Define base URL
baseurl = urlparse(workflow.current_basedir.get_path_or_uri(secret_free=True))


include: "rules/utils.smk"
include: "rules/setup.smk"


# Load modules
module workflow_trim:
    snakefile:
        github("GeoGenetics/ngs-trim", path="workflow/Snakefile", tag="v0.5.7")
    config:
        {"units": units, "cfg": config["trim"]}


use rule * from workflow_trim as trim_*


module workflow_derep:
    snakefile:
        github("GeoGenetics/ngs-derep", path="workflow/Snakefile", tag="v0.7.0")
    config:
        {"units": units, "cfg": config["derep"]}


use rule * from workflow_derep as derep_*


module workflow_taxon:
    snakefile:
        github("GeoGenetics/ngs-taxon", path="workflow/Snakefile", tag="v0.12.0")
    config:
        {"units": units, "cfg": config["taxon"]}


use rule * from workflow_taxon as taxon_*


pathvars:
    stats="stats",
    temp="temp",
    reads="reads",
    shards="shards",


onsuccess:
    print("aeDNA workflow finished successfully!")


onerror:
    print("aeDNA workflow finished with an error!")


##################
### PRINT INFO ###
##################
import git
import json
import datetime
from snakemake.logging import logger

base_dir = Path(workflow.basedir).resolve(strict=True)
repo = git.Repo(base_dir.parent)
tag_recent = [
    [tag.name, commit.hexsha]
    for commit in repo.iter_commits()
    for tag in repo.tags
    if commit.hexsha == tag.commit.hexsha
][0]
logger.info(
    "Git commit: {commit_hash} [{tag_flag}{commit_tag}] ({commit_time})".format(
        commit_hash=repo.head.commit.hexsha,
        commit_time=repo.head.commit.committed_datetime.strftime("%Y-%m-%d %H:%M:%S"),
        tag_flag="" if tag_recent[1] == repo.head.commit.hexsha else ">",
        commit_tag=tag_recent[0],
    )
)
config_json = json.dumps(config, sort_keys=True).encode("utf-8")
logger.info(f"Config JSON: {config_json}")
# Log current samples
logger.info("Samples:")
logger.info(samples.to_string(index=False))
logger.info("Units:")
logger.info(str(units.index))


####################
### Target Rules ###
####################


rule multiqc_trim:
    input:
        rules.trim_multiqc.input,
        config=base_dir / "resources/multiqc_config.yaml",
    output:
        html="reports/multiqc.trim.html",
        data="reports/multiqc_data.trim.zip",
    log:
        "logs/reports/multiqc.trim.log",
    benchmark:
        "benchmarks/reports/multiqc.trim.jsonl"
    localrule: True
    threads: 1
    resources:
        mem=lambda w, attempt: f"{10* attempt} GiB",
        runtime=lambda w, attempt: f"{30* attempt} m",
    params:
        extra=f"--force --clean-up " + config["report"]["multiqc"],
    wrapper:
        "v9.15.0/bio/multiqc"


rule target_trim:
    input:
        rules.multiqc_trim.output,
        rules.trim_all.input.res,
    message:
        "Read trimming finished successfully!"


rule multiqc_trim_upload:
    input:
        rules.target_trim.input,
        zip=rules.multiqc_trim.output.data,
    output:
        "stats/reports/multiqc_trim.upload.flag",
    log:
        "logs/reports/multiqc_trim.upload.log",
    localrule: True
    conda:
        "envs/multiqc_upload.yaml"
    threads: 1
    resources:
        mem=lambda w, attempt: f"{1* attempt} GiB",
        runtime=lambda w, attempt: f"{30* attempt} m",
    params:
        db_url=config["report"].get("multiqc_db_url"),
    shell:
        """
        python {base_dir}/scripts/multiqc_upload.py --db-upload {input.zip} --db-url {params.db_url} --log-level INFO 2>{log}
        cut -d ":" -f 4- {log} >{output[0]}
        """


#####


use rule multiqc_trim as multiqc_derep with:
    input:
        rules.trim_multiqc.input,
        rules.derep_multiqc.input,
        config=base_dir / "resources/multiqc_config.yaml",
    output:
        html="reports/multiqc.derep.html",
        data="reports/multiqc_data.derep.zip",
    log:
        "logs/reports/multiqc.derep.log",
    benchmark:
        "benchmarks/reports/multiqc.derep.jsonl"


rule target_derep:
    input:
        rules.multiqc_derep.output,
        rules.derep_all.input.res,
    message:
        "Read dereplication finished successfully!"


use rule multiqc_trim_upload as multiqc_derep_upload with:
    input:
        rules.target_derep.input,
        zip=rules.multiqc_derep.output.data,
    output:
        touch("stats/reports/multiqc_derep.upload.flag"),
    log:
        "logs/reports/multiqc_derep.upload.log",


#####


use rule multiqc_derep as multiqc_taxon with:
    input:
        rules.trim_multiqc.input,
        rules.derep_multiqc.input,
        rules.taxon_multiqc.input,
        config=base_dir / "resources/multiqc_config.yaml",
    output:
        html="reports/multiqc.taxon.html",
        data="reports/multiqc_data.taxon.zip",
    log:
        "logs/reports/multiqc.taxon.log",
    benchmark:
        "benchmarks/reports/multiqc.taxon.jsonl"


rule target_taxon:
    default_target: True
    input:
        rules.multiqc_taxon.output,
        rules.taxon_all.input.res,
    message:
        "Taxonomic assignment finished successfully!"


use rule multiqc_trim_upload as multiqc_taxon_upload with:
    input:
        rules.target_taxon.input,
        zip=rules.multiqc_taxon.output.data,
    output:
        touch("stats/reports/multiqc_taxon.upload.flag"),
    log:
        "logs/reports/multiqc_taxon.upload.log",
