snakemake.utils.min_version("8.11.2")

# Define wrapper versions
wrapper_ver = "v3.12.0"

# Load modules
module workflow_trim:
    snakefile:
        github("GeoGenetics/ngs-trim", path="workflow/Snakefile", tag="v0.4.3")
    config:
        config
use rule * from workflow_trim as trim_*

module workflow_derep:
    snakefile:
        github("GeoGenetics/ngs-derep", path="workflow/Snakefile", tag="v0.4.3")
    config:
        config
use rule * from workflow_derep as derep_*

module workflow_taxon:
    snakefile:
        github("GeoGenetics/ngs-taxon", path="workflow/Snakefile", tag="v0.6.0")
    config:
        config
use rule * from workflow_taxon as taxon_*



include: "rules/utils.smk"
include: "rules/setup.smk"



##################
### PRINT INFO ###
##################
import pwd
import git
import json
import hashlib
import datetime
from snakemake.logging import logger
base_dir = Path(workflow.basedir)
repo = git.Repo(base_dir.parent)
logger.info(f"Snakemake version: {snakemake.common.__version__}")
logger.info("Git commit: {commit_hash} [{tag_flag}{commit_tag}] ({commit_time})".format(
        commit_hash = repo.head.commit.hexsha,
        commit_time = repo.head.commit.committed_datetime.strftime("%Y-%m-%d %H:%M:%S"),
        tag_flag = next(("" for tag in repo.tags if tag.commit == repo.head.commit), ">"),
        commit_tag = repo.git.tag(l=True, sort="authordate").split("\n")[-1],
))
logger.info("Run started: {time} ({user})".format(time = str(datetime.datetime.now()), user = pwd.getpwuid(os.getuid())[0]))
logger.info(f"Workflow base dir: {base_dir}")
logger.info(f"Executing in: {workflow.workdir_init}")
config_json = json.dumps(config, sort_keys=True).encode('utf-8')
logger.info("Config JSON MD5: {md5sum} ({json})".format(md5sum = hashlib.md5(config_json).hexdigest(), json = config_json))
# Log current samples
logger.info("Samples:")
logger.info(samples.to_string(index=False))
logger.info("Units:")
logger.info(units.index)



####################
### Target Rules ###
####################

rule multiqc_trim:
    input:
        rules.trim_multiqc.input,
        config = base_dir / "resources/multiqc_config.yaml",
    output:
        html = "reports/multiqc.trim.html",
        data = "reports/multiqc_data.trim.zip",
    log:
        "logs/reports/multiqc.trim.log"
    benchmark:
        "benchmarks/reports/multiqc.trim.log"
    params:
        extra = f"--force " + check_cmd(config["report"]["multiqc"], forbidden_args = ["-n", "--filename", "-o", "--outdir", "--data-dir", "--no-data-dir", "-z", "--zip-data-dir", "--no-report", "--pdf", "--version", "-h", "--help"]),
    localrule: True
    threads: 1
    resources:
        mem = lambda w, attempt: f"{10 * attempt} GiB",
        runtime = lambda w, attempt: f"{30 * attempt} m",
    wrapper:
        f"{wrapper_ver}/bio/multiqc"

rule multiqc_trim_upload:
    input:
        json=rules.multiqc_trim.output.data,
    output:
        touch("stats/reports/multiqc_trim.upload.flag"),
    log:
        "logs/reports/multiqc_trim.upload.log"
    params:
        db_url=config["report"]["multiqc_db_url"],
    conda:
        "envs/multiqc_upload.yaml"
    localrule: True
    threads: 1
    resources:
        mem = lambda w, attempt: f"{1 * attempt} GiB",
        runtime = lambda w, attempt: f"{30 * attempt} m",
    shell:
        "python scripts/multiqc_upload.py --json {input.json} --db-url {params.db_url} --log-level INFO 2> {log}"

rule target_trim:
    input:
        rules.multiqc_trim_upload.output if config["report"]["multiqc_db_url"] else rules.multiqc_trim.output,
        rules.trim_all.input.res,
    message:
        "Read trimming finished successfully!"


#####

use rule multiqc_trim as multiqc_derep with:
    input:
        rules.trim_multiqc.input,
        rules.derep_multiqc.input,
        config = base_dir / "resources/multiqc_config.yaml",
    output:
        html = "reports/multiqc.derep.html",
        data = "reports/multiqc_data.derep.zip",
    log:
        "logs/reports/multiqc.derep.log"
    benchmark:
        "benchmarks/reports/multiqc.derep.log"

use rule multiqc_trim_upload as multiqc_derep_upload with:
    input:
        json=rules.multiqc_derep.output.data,
    output:
        touch("stats/reports/multiqc_derep.upload.flag"),
    log:
        "logs/reports/multiqc_derep.upload.log"

rule target_derep:
    input:
        rules.multiqc_derep_upload.output if config["report"]["multiqc_db_url"] else rules.multiqc_derep.output,
        rules.derep_all.input.res,
    message:
        "Read dereplication finished successfully!"


#####

use rule multiqc_derep as multiqc_taxon with:
    input:
        rules.trim_multiqc.input,
        rules.derep_multiqc.input,
        rules.taxon_multiqc.input,
        config = base_dir / "resources/multiqc_config.yaml",
    output:
        html = "reports/multiqc.taxon.html",
        data = "reports/multiqc_data.taxon.zip",
    log:
        "logs/reports/multiqc.taxon.log"
    benchmark:
        "benchmarks/reports/multiqc.taxon.log"

use rule multiqc_trim_upload as multiqc_taxon_upload with:
    input:
        json=rules.multiqc_taxon.output.data,
    output:
        touch("stats/reports/multiqc_taxon.upload.flag"),
    log:
        "logs/reports/multiqc_taxon.upload.log"

rule target_taxon:
    input:
        rules.multiqc_taxon_upload.output if config["report"]["multiqc_db_url"] else rules.multiqc_taxon.output,
        rules.taxon_all.input.res,
    message:
        "Taxonomic assignment finished successfully!"
    default_target: True
