
# - Only tested with Phred33 quality scores

samples: config/samples.tsv

units: config/units.tsv



#############
### READS ###
#############
trim:
  trim:
    activate: true
    tool: adapterremoval
    params: "--trimns --maxns 10 --trimqualities --minlength 30 --mask-degenerate-bases --seed 12345"

  # Ignored for SE
  collapse:
    activate: true
    params: "--collapse-conservatively"

derep:
  extension:
    activate: false
    k: 16
    params: "ibb=t prefilter=0 el=100 er=100 ecc=f ecco=f ignorebadquality extendrollback=0"

  derep:
    activate: true
    # vsearch or seqkit
    tool: seqkit
    params: ""

  low_complex:
    params: "entropy=0.7 entropywindow=30 entropyk=4"



#############
### ALIGN ###
#############
taxon:
  taxonomy:
    nodes: "data/taxdump/nodes.dmp"
    names: "data/taxdump/names.dmp"

  ref:
    hires_organelles_viruses_smags:
      n_shards: 2
      path: "/staging/hash_tables/hires-organelles-viruses-smags.{n_shard}"
      map: &map_prok_dragen
        tool: dragen
        params: "--Aligner.global=1 --Aligner.match-score=0 --Aligner.match-n-score=-1 --Aligner.mismatch-pen=4 --Aligner.gap-open-pen=0 --Aligner.gap-ext-pen=4 --Aligner.aln-min-score=0 --Aligner.min-score-coeff=-0.4 --Aligner.sec-aligns=2000 --Aligner.supp-aligns=0 --Aligner.hard-clips=0 --Aligner.sec-score-delta=100 --Mapper.edit-mode=1 --Mapper.max-seed-freq=256 --Mapper.reduce-seed-ext=1 --Mapper.intvl-target-hits=256 --Mapper.intvl-max-hits=256 --Mapper.intvl-sample-hits=256 --Mapper.seed-density=1.0 --Mapper.edit-seed-num=80 --Mapper.edit-read-len=100 --Mapper.edit-chain-limit=29 --filter-flags-from-output=4"
      acc2taxid: "data/prok.acc2taxid.gz"
    human_genome:
      n_shards: 1
      path: "/staging/hash_tables/GCF_000001405.40_GRCh38.p14_genomic"
      map:
        <<: *map_prok_dragen
      acc2taxid: "data/human.acc2taxid.gz"
    refseq_mitoch:
      n_shards: 1
      path: "/staging/hash_tables/refseq_mitochondrion.genomic/"
      map: &map_euk_dragen
        tool: dragen
        params: "--Aligner.global=1 --Aligner.match-score=0 --Aligner.match-n-score=-1 --Aligner.mismatch-pen=4 --Aligner.gap-open-pen=0 --Aligner.gap-ext-pen=4 --Aligner.aln-min-score=0 --Aligner.min-score-coeff=-0.4 --Aligner.sec-aligns=2000 --Aligner.supp-aligns=0 --Aligner.hard-clips=0 --Aligner.sec-score-delta=100 --Mapper.edit-mode=0 --Mapper.max-seed-freq=256 --Mapper.reduce-seed-ext=1 --Mapper.intvl-target-hits=256 --Mapper.intvl-max-hits=256 --Mapper.intvl-sample-hits=256 --Mapper.seed-density=1.0 --Mapper.edit-seed-num=80 --Mapper.edit-read-len=100 --Mapper.edit-chain-limit=29 --filter-flags-from-output=4"
      acc2taxid: "data/mitoch.acc2taxid.gz"
    core_nt:
      n_shards: 4
      path: "/staging/hash_tables/core_nt.{n_shard}"
      map:
        <<: *map_euk_dragen
      acc2taxid: "data/core_nt.acc2taxid.gz"

  filter:
    saturated_reads:
      activate: true
      n_alns: 500

  unicorn:
    refstats:
      params: "--minrefl 1 --minreads 1 --rank genus"
    taxstats:
      params: "-k 17 --minrefl  1 --minreads 1 --minmani 0 --minalnas -Inf --maxdust 100"


  metadmg:
    damage:
      params: "--print_length 15"

    lca:
      params: "--fix_ncbi 0 --how_many 15 --sim_score_low 0.95 --weight_type 0 --edit_dist_max 10000 --lca_rank genus"

    dfit:
      params: "--nopt 5 --showfits 2 --seed 12345"


############
## REPORT ##
############
report:
  multiqc: "--no-ai --verbose --cl-config 'custom_logo: data/KU_long.png' --cl-config 'custom_logo_title: CAEG - Center for Ancient Environmental Genomics' --cl-config 'custom_logo_url: https://globe.ku.dk/research/caeg/'"
  multiqc_db_url: "test_qc.sqlite"
