$schema: "https://json-schema.org/draft/2020-12/schema"

description: aeDNA workflow configuration file

type: object
properties:

  samples:
    type: string

  units:
    type: string

  trim:
    type: object

  derep:
    type: object

  prefilter:
    type: object

  euk:
    type: object

  report:
    type: object
    properties:
      multiqc:
        type: string
        pattern: "^((?!\b--?(n|filename|o|outdir|data-dir|no-data-dir|z|zip-data-dir|no-report|pdf|version|clean-up|no-clean-up|h|help)[ =]).)*$"
      multiqc_db_url:
        type: string
    required:
      - multiqc
      - multiqc_db_url

required:
  - trim
  - derep
  - prefilter
  - euk
  - report
